# use this if You have separate repositories for roles or external roles from Ansible Galaxy
# ansible-galaxy install -r requirements.yml
- src: https://github.com/geerlingguy/ansible-role-apache.git
  scm: git
  version: c8c80dd3ac6fdefa37bddb12ed80842f6ec8e49f
  name: galaxy-apache

- src: https://github.com/ahuffman/ansible-resolv.git
  scm: git
  version: 6d9d7e56a4348634a7c188caaea5ca93941f391b
  name: galaxy-resolv
