---
- hosts: client
  become: yes
  vars:
    resolv_nameservers:
      - "{{ hostvars[groups['ns'][0]]['ansible_host'] }}"
    resolv_domain: "{{ hostvars[groups['ns'][0]]['bind_zone_name'] }}"
    resolv_search:
      - "{{ hostvars[groups['ns'][0]]['bind_zone_name'] }}"
  roles:
    - galaxy-resolv

- hosts: client
  tasks:
    - name: Test that web server and DNS is working as expected
      uri:
        url: "http://www.{{ hostvars[groups['ns'][0]]['bind_zone_name'] }}"
        return_content: yes
      register: webpage
    
    - name: Show webpage when in verbose mode
      debug:
        var: webpage.content
        verbosity: 1

    - name: Check about AWESOME in the page content
      assert:
        that: "'AWESOME' in webpage.content"
        msg: "String 'AWESOME' should be in webpage. Instead we saw {{ webpage.content }}"
